### ISSUE TITLE
Running multiple simulations in a single Python script

### ISSUE THREAD

**Issue by cfuria** [LLNL/UEDGE#20]
I am trying to run multiple PyUEDGE simulations in a loop using the Jupyter notebook. Here is the pseudocode:
````python
from uedge import *
...
for i in range(n):
  #update some parameters in the bbb package
  bbb.exmain()
  #save some measurements
````

I am noticing some very interesting results. Once a certain threshold (on the order of 10) for n is exceeded, the majority of the later simulations do not run to the full 30 iterations, converging very quickly with `iterm = 1` and very low `fnrm` values. This wouldn't be an issue in and of itself, but when I run a certain initial configuration in an environment where 100 simulations have already been run in the manner above, the measurements for te, ti, etc. are different than what I get when I run the same configuration in a fresh environment where no prior simulations were run. As a control, when I run the same initial configuration in two separate, fresh environments, I get identical measurements, so this indicates that something is going wrong. 

To me, it seems like some backend variables are not being properly reset between the sequential executions of `bbb.exmain()`. I am new to UEDGE, so any help on this issue would be great.

**Comment by trognlien** [comment]
It would be useful to see the output (iteration count, fnrm, etc)  from the iterations of the run starting after, say 100 iterations, and a second one starting from a fresh environment.  No need to show all of the iterations, but only to include as least the transition where the two methods give the same result and then begin to differ, or if they differ even on the first iteration, show the two outputs from that.

------
Thomas D. Rognlien                                     Email: ***@***.******@***.***>
L-440 (B3725, R432)                                   Tel:  925-422-9830
LLNL, 7000 East Ave, P.O. Box 808           Admin support: 925-422-7446
Livermore, CA 94551



From: cfuria ***@***.***>
Reply-To: LLNL/UEDGE ***@***.***>
Date: Tuesday, July 13, 2021 at 11:25 AM
To: LLNL/UEDGE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LLNL/UEDGE] Running multiple simulations in a single Python script (#20)


I am trying to run multiple PyUEDGE simulations in a loop using the Jupyter notebook. Here is the pseudocode:

from uedge import *

...

for i in range(n):

  #update some parameters in the bbb package

  bbb.exmain()

  #save some measurements

I am noticing some very interesting results. Once a certain threshold (on the order of 10) for n is exceeded, the majority of the later simulations do not run to the full 30 iterations, converging very quickly with iterm = 1 and very low fnrm values. This wouldn't be an issue in and of itself, but when I run a certain initial configuration in an environment where 100 simulations have already been run in the manner above, the measurements for te, ti, etc. are different than what I get when I run the same configuration in a fresh environment where no prior simulations were run. As a control, when I run the same initial configuration in two separate, fresh environments, I get identical measurements, so this indicates that something is going wrong.

To me, it seems like some variables are not being properly reset between the sequential executions of bbb.exmain(). I am new to UEDGE, so any help on this issue would be great.

**Comment by cfuria** [comment]
Results from the run starting after 100 simulations:
````
UEDGE $Name: V7_09_02 $
Wrote file "gridue" with runid:    EFITD    09/07/90      # 66832 ,2384ms��������            

 ***** Grid generation has been completed
  Updating Jacobian, npe =                      1
 iter=    0 fnrm=     0.4884085628076241     nfe=      1
  Updating Jacobian, npe =                      2
 iter=    1 fnrm=     0.4671420091454486     nfe=     24
 iter=    2 fnrm=     0.4411713449131697     nfe=     50
 iter=    3 fnrm=     0.4206699610874590     nfe=     86
 iter=    4 fnrm=     0.4130005131324361     nfe=    123
 iter=    5 fnrm=     0.4087938996934226     nfe=    160
  Updating Jacobian, npe =                      3
 iter=    6 fnrm=     0.3852795681315921     nfe=    175
 iter=    7 fnrm=     0.3579047446683835     nfe=    193
 iter=    8 fnrm=     0.3264477480360225     nfe=    215
 iter=    9 fnrm=     0.3291915675412144     nfe=    247
 iter=   10 fnrm=     0.2985548946641430     nfe=    275
  Updating Jacobian, npe =                      4
 iter=   11 fnrm=     0.2616509852150688     nfe=    293
 iter=   12 fnrm=     0.2525471794564058     nfe=    316
 iter=   13 fnrm=     0.2506493148302380     nfe=    351
 iter=   14 fnrm=     0.2304580279914706     nfe=    385
 iter=   15 fnrm=     0.1602699754169653     nfe=    421
  Updating Jacobian, npe =                      5
 iter=   16 fnrm=     0.5322574291557221E-01 nfe=    434
 iter=   17 fnrm=     0.9899483298349073E-02 nfe=    450
 iter=   18 fnrm=     0.9593463464214905E-03 nfe=    466
 iter=   19 fnrm=     0.1721070907466653E-05 nfe=    483
 iter=   20 fnrm=     0.3825405343555981E-09 nfe=    506
  Updating Jacobian, npe =                      6
 iter=   21 fnrm=     0.9584557053340898E-11 nfe=    526


 nksol ---  iterm = 1.
            maxnorm(sf*f(u)) .le. ftol, where maxnorm() is
            the maximum norm function.  u is probably an
            approximate root of f.
 Interpolants created; mype =                   -1
````
Results from the run starting after 0 simulations (no other runs):
````
UEDGE $Name: V7_09_02 $
Wrote file "gridue" with runid:    EFITD    09/07/90      # 66832 ,2384ms��������            

 ***** Grid generation has been completed
  Updating Jacobian, npe =                      1
 iter=    0 fnrm=      2.136642210096055     nfe=      1
  Updating Jacobian, npe =                      2
 iter=    1 fnrm=      2.121503682570631     nfe=     13
 iter=    2 fnrm=      2.032286982296977     nfe=     30
 iter=    3 fnrm=      1.960579474356897     nfe=     52
 iter=    4 fnrm=      1.894459393842296     nfe=     79
 iter=    5 fnrm=      1.845530876385033     nfe=    114
  Updating Jacobian, npe =                      3
 iter=    6 fnrm=      1.764286058407941     nfe=    133
 iter=    7 fnrm=      1.725418282617423     nfe=    155
 iter=    8 fnrm=      1.729785803551428     nfe=    181
 iter=    9 fnrm=      1.736277375408835     nfe=    213
 iter=   10 fnrm=      1.754802041641710     nfe=    242
  Updating Jacobian, npe =                      4
 iter=   11 fnrm=      1.762044620546933     nfe=    261
 iter=   12 fnrm=      1.764575437147577     nfe=    282
 iter=   13 fnrm=      1.768529819650052     nfe=    307
 iter=   14 fnrm=      1.773356828914952     nfe=    337
 iter=   15 fnrm=      1.789545013500852     nfe=    374
  Updating Jacobian, npe =                      5
 iter=   16 fnrm=      1.794886548613142     nfe=    391
 iter=   17 fnrm=      1.802188626137893     nfe=    408
 iter=   18 fnrm=      1.778841141499653     nfe=    429
 iter=   19 fnrm=      1.791436323790826     nfe=    451
 iter=   20 fnrm=      1.793130768578333     nfe=    469
  Updating Jacobian, npe =                      6
 iter=   21 fnrm=      1.776943066727186     nfe=    484
 iter=   22 fnrm=      1.771746727188482     nfe=    501
 iter=   23 fnrm=      1.772183898681232     nfe=    521
 iter=   24 fnrm=      1.775974514502974     nfe=    546
 iter=   25 fnrm=      1.776224036709406     nfe=    574
  Updating Jacobian, npe =                      7
 iter=   26 fnrm=      1.780423723690242     nfe=    593
 iter=   27 fnrm=      1.780172675581789     nfe=    612
 iter=   28 fnrm=      1.784123582634681     nfe=    632
 iter=   29 fnrm=      1.783336972028313     nfe=    650
 iter=   30 fnrm=      1.786552326493947     nfe=    670


 nksol ---  iterm = 4.
            the maximum allowable number of nonlinear
            iterations has been reached.
 Interpolants created; mype =                   -1
````
I haven't figured out the exact value of n where the results start to diverge, but my guess is around 50 simulations. That is where the first simulations with <30 iterations and `iterm = 1` start to appear.

**Comment by trognlien** [comment]
Thanks, the output is useful.  UEDGE begins with some initial profiles that typically are not a solution for a given set of input parameters.  During the course of the iterations shown, a converged solution at the given timestep (dtreal) is only found if fnrm < bbb.ftol.  Thus, the first case below (started after 100 iterations), does converge (iterm=1), and the next case in your “i” loop from the first email message will begin from this new converged state.  I assume you are slowly changing some input parameter for each “i”.   Consequently, this first case below is actually producing converged results for each “i”.

In contrast, your “fresh start” case below does not converge for i=1, so for i=2,..., UEDGE again restarts from the original input profiles.  The “results” after 30 iteration, but with fnrm > bbb.ftol are then meaningless – they are just the state of the variables after 30 iterations, but don’t provide a converged result, i.e., a successful timestep.  Apparently if you keep running this case, eventually, at about i=50 from your comments, UEDGE finally produces its first converged solution as you change some parameter with each new “i”.  From this point forward, each case that reaches fnrm < bbb.ftol and exits with the message that iterm=1 is a converged solution, and those results are meaningful.

If you want to perform an input parameter scan as “i” is changed, you should first obtain a solution for the i=1 case before beginning the scan, and then use that solution as your starting profile (you can save this initial solution into an HDF5 file, and then read that in to begin your scan.  What test case are you beginning from?  If it is one from GitHub directly, we should fix it so that it provides an intial solution for the test input file.  Please let me know.

------
Thomas D. Rognlien                                     Email: ***@***.******@***.***>
L-440 (B3725, R432)                                   Tel:  925-422-9830
LLNL, 7000 East Ave, P.O. Box 808           Admin support: 925-422-7446
Livermore, CA 94551



From: cfuria ***@***.***>
Reply-To: LLNL/UEDGE ***@***.***>
Date: Tuesday, July 13, 2021 at 12:14 PM
To: LLNL/UEDGE ***@***.***>
Cc: "Rognlien, Tom" ***@***.***>, Comment ***@***.***>
Subject: Re: [LLNL/UEDGE] Running multiple simulations in a single Python script (#20)


Results from the run starting after 100 simulations:

UEDGE $Name: V7_09_02 $

Wrote file "gridue" with runid:    EFITD    09/07/90      # 66832 ,2384ms��������



 ***** Grid generation has been completed

  Updating Jacobian, npe =                      1

 iter=    0 fnrm=     0.4884085628076241     nfe=      1

  Updating Jacobian, npe =                      2

 iter=    1 fnrm=     0.4671420091454486     nfe=     24

 iter=    2 fnrm=     0.4411713449131697     nfe=     50

 iter=    3 fnrm=     0.4206699610874590     nfe=     86

 iter=    4 fnrm=     0.4130005131324361     nfe=    123

 iter=    5 fnrm=     0.4087938996934226     nfe=    160

  Updating Jacobian, npe =                      3

 iter=    6 fnrm=     0.3852795681315921     nfe=    175

 iter=    7 fnrm=     0.3579047446683835     nfe=    193

 iter=    8 fnrm=     0.3264477480360225     nfe=    215

 iter=    9 fnrm=     0.3291915675412144     nfe=    247

 iter=   10 fnrm=     0.2985548946641430     nfe=    275

  Updating Jacobian, npe =                      4

 iter=   11 fnrm=     0.2616509852150688     nfe=    293

 iter=   12 fnrm=     0.2525471794564058     nfe=    316

 iter=   13 fnrm=     0.2506493148302380     nfe=    351

 iter=   14 fnrm=     0.2304580279914706     nfe=    385

 iter=   15 fnrm=     0.1602699754169653     nfe=    421

  Updating Jacobian, npe =                      5

 iter=   16 fnrm=     0.5322574291557221E-01 nfe=    434

 iter=   17 fnrm=     0.9899483298349073E-02 nfe=    450

 iter=   18 fnrm=     0.9593463464214905E-03 nfe=    466

 iter=   19 fnrm=     0.1721070907466653E-05 nfe=    483

 iter=   20 fnrm=     0.3825405343555981E-09 nfe=    506

  Updating Jacobian, npe =                      6

 iter=   21 fnrm=     0.9584557053340898E-11 nfe=    526





 nksol ---  iterm = 1.

            maxnorm(sf*f(u)) .le. ftol, where maxnorm() is

            the maximum norm function.  u is probably an

            approximate root of f.

 Interpolants created; mype =                   -1

Results from the run starting after 0 simulations (no other runs):

UEDGE $Name: V7_09_02 $

Wrote file "gridue" with runid:    EFITD    09/07/90      # 66832 ,2384ms��������



 ***** Grid generation has been completed

  Updating Jacobian, npe =                      1

 iter=    0 fnrm=      2.136642210096055     nfe=      1

  Updating Jacobian, npe =                      2

 iter=    1 fnrm=      2.121503682570631     nfe=     13

 iter=    2 fnrm=      2.032286982296977     nfe=     30

 iter=    3 fnrm=      1.960579474356897     nfe=     52

 iter=    4 fnrm=      1.894459393842296     nfe=     79

 iter=    5 fnrm=      1.845530876385033     nfe=    114

  Updating Jacobian, npe =                      3

 iter=    6 fnrm=      1.764286058407941     nfe=    133

 iter=    7 fnrm=      1.725418282617423     nfe=    155

 iter=    8 fnrm=      1.729785803551428     nfe=    181

 iter=    9 fnrm=      1.736277375408835     nfe=    213

 iter=   10 fnrm=      1.754802041641710     nfe=    242

  Updating Jacobian, npe =                      4

 iter=   11 fnrm=      1.762044620546933     nfe=    261

 iter=   12 fnrm=      1.764575437147577     nfe=    282

 iter=   13 fnrm=      1.768529819650052     nfe=    307

 iter=   14 fnrm=      1.773356828914952     nfe=    337

 iter=   15 fnrm=      1.789545013500852     nfe=    374

  Updating Jacobian, npe =                      5

 iter=   16 fnrm=      1.794886548613142     nfe=    391

 iter=   17 fnrm=      1.802188626137893     nfe=    408

 iter=   18 fnrm=      1.778841141499653     nfe=    429

 iter=   19 fnrm=      1.791436323790826     nfe=    451

 iter=   20 fnrm=      1.793130768578333     nfe=    469

  Updating Jacobian, npe =                      6

 iter=   21 fnrm=      1.776943066727186     nfe=    484

 iter=   22 fnrm=      1.771746727188482     nfe=    501

 iter=   23 fnrm=      1.772183898681232     nfe=    521

 iter=   24 fnrm=      1.775974514502974     nfe=    546

 iter=   25 fnrm=      1.776224036709406     nfe=    574

  Updating Jacobian, npe =                      7

 iter=   26 fnrm=      1.780423723690242     nfe=    593

 iter=   27 fnrm=      1.780172675581789     nfe=    612

 iter=   28 fnrm=      1.784123582634681     nfe=    632

 iter=   29 fnrm=      1.783336972028313     nfe=    650

 iter=   30 fnrm=      1.786552326493947     nfe=    670





 nksol ---  iterm = 4.

            the maximum allowable number of nonlinear

            iterations has been reached.

 Interpolants created; mype =                   -1

I haven't figured out the exact value of n where the results start to diverge, but my guess is around 50 simulations. That is where the first simulations with <30 iterations and iterm = 1 start to appear.

**Comment by cfuria** [comment]
Thank you, the response helped clarify a lot for me. My current goal is to find converged solutions for different input parameters at the same timestep. Is there a way to achieve this in a single script without progressing the timestep after each convergence? I am using the test case from the `LLNL/UEDGE/jupyter` folder, and I believe it is starting out with an initial solution stored in an HDF5 file. In this case, would it still be necessary to obtain a solution for the i=1 parameters?

**Comment by trognlien** [comment]
The jupyter test case on GitHub in LLNL/UEDGE/jupyter is for an older version of UEDGE and it has an input parameter setting that is no longer valid.  To get a new input file, you have two choices:

    (1) download the new UEDGE package from GitHub by going to the tab on the left top of the LLNL/UEDGE page labeled “tags” and from there download the zip or gzip package.  (You can also get this newest package from the tab on the right-hand side of the GitHub page labeled “releases”).
    (2), you can simply change one line setting bbb.iphibcc in your existing case_setup.py file to read:

bbb.iphibcc = 3         #set bbb.phi[,1] uniform poloidally & ey=eycore
   The output from UEDGE should then look like:
=========================

UEDGE $Name: V7_09_02 $
 Wrote file "gridue" with runid:    EFITD    09/07/90      # 66832 ,2384ms

***** Grid generation has been completed
  Updating Jacobian, npe =                      1
iter=    0 fnrm=      2.166387192180601     nfe=      1
  Updating Jacobian, npe =                      2
iter=    1 fnrm=      1.928769360089391     nfe=      9
iter=    2 fnrm=      1.727871802175635     nfe=     20
iter=    3 fnrm=      1.567934612037736     nfe=     35
iter=    4 fnrm=      1.410309031484570     nfe=     53
iter=    5 fnrm=      1.239057927892954     nfe=     85
  Updating Jacobian, npe =                      3
iter=    6 fnrm=      1.168360365396128     nfe=     95
iter=    7 fnrm=      1.015732382221925     nfe=    109
iter=    8 fnrm=     0.8044625501173911     nfe=    124
iter=    9 fnrm=     0.6757626982214426     nfe=    148
iter=   10 fnrm=     0.5750709816062617     nfe=    182
  Updating Jacobian, npe =                      4
iter=   11 fnrm=     0.5206303769532492     nfe=    192
iter=   12 fnrm=     0.5682214285918914     nfe=    221
iter=   13 fnrm=     0.3580771582481752     nfe=    241
iter=   14 fnrm=     0.3674454388484675     nfe=    273
iter=   15 fnrm=     0.3583264932847002     nfe=    300
  Updating Jacobian, npe =                      5
iter=   16 fnrm=     0.8164069342882538E-01 nfe=    306
iter=   17 fnrm=     0.3397346123579930E-01 nfe=    317
iter=   18 fnrm=     0.1486037946952937E-02 nfe=    328
iter=   19 fnrm=     0.2074050652194881E-05 nfe=    341
iter=   20 fnrm=     0.9492056825962371E-11 nfe=    361


nksol ---  iterm = 1.
            maxnorm(sf*f(u)) .le. ftol, where maxnorm() is
            the maximum norm function.  u is probably an
            approximate root of f.
Interpolants created; mype =                   -1
======================

This case has an “infinite” timestep with bbb.dtreal=1.e20, so the final solution is a steady state.  If you want to save this solution into an hdf5 file, you should issue the following commands:

from uedge.hdf5 import *
hdf5_save('solution1.hdf5')

where ‘solution1.hdf5’ is a name of your choosing.  To restore this solution into some other UEDGE simulation, you would issue the command:

hdf5_restore(‘solution1.hdf5’)

  Finally, to try to answer your question below.  You asking about finding a set of converged solutions for a given (finite?) timestep as some parameter is varied.  I am unsure of your application, or of the utility of such a sequence (we usually save final steady state solutions as some parameter is varied), but here is a strategy.  If you alway want to restart from the same plasma state, you need to restore that solution before each UEDGE timestep as otherwise UEDGE will continue from the most recent successful solution in your python session.  So, identify the hdf5 solution file you want to restart from and call it something like ‘initial_soln.hdf5’.  The input parameter you want to change is represented here by bbb.xyz, and the timestep you want to consider is bbb.dtreal (the actual variable name for UEDGE).  Then within a python session or script, you would have the following sequence:

bbb.dtreal = 1.e-3

hdf5_restore(‘initial_soln.hdf5’)
bbb.xyz = 1
bbb.exmain()
hdf5_save(‘xyz=1_soln’)

hdf5_restore(‘initial_soln.hdf5’)
bbb.xyz = 2
bbb.exmain()
hdf5_save(‘xyz=2_soln’)

... etc. for various bbb.xyz values you want.

Of course, you want to be sure that each of these cases represent a converged solution, so there should be an if-test on the output parameter bbb.iterm = 1 before saving the solution to an hdf5 file.

   Let me know if you have questions.

------
Thomas D. Rognlien                                     Email: ***@***.******@***.***>
L-440 (B3725, R432)                                   Tel:  925-422-9830
LLNL, 7000 East Ave, P.O. Box 808           Admin support: 925-422-7446
Livermore, CA 94551



From: cfuria ***@***.***>
Reply-To: LLNL/UEDGE ***@***.***>
Date: Tuesday, July 13, 2021 at 3:38 PM
To: LLNL/UEDGE ***@***.***>
Cc: "Rognlien, Tom" ***@***.***>, Comment ***@***.***>
Subject: Re: [LLNL/UEDGE] Running multiple simulations in a single Python script (#20)


Thank you, the response helped clarify a lot for me. My current goal is to find converged solutions for different input parameters at the same timestep. Is there a way to achieve this in a single script without progressing the timestep after each convergence? I am using the test case from the LLNL/UEDGE/jupyter folder, and I believe it is starting out with an initial solution stored in an HDF5 file. In this case, would it still be necessary to obtain a solution for the i=1 parameters?

**Comment by cfuria** [comment]
The above solution works.
