### ISSUE TITLE
Xerrab calls in PyUEDGE induces Segfault

### ISSUE THREAD

**Issue by holm10** [LLNL/UEDGE#49]
**Describe the bug**
Xerrab calls in the UEDGE source induces Segfaults for the Python version.

**Expected behavior**
Output error message, return user to prompt.

**Additional context**
Exacerbates minor bugs to Segfaults, see e.g. #48

**Comment by holm10** [comment]
Error was traced to missing flat_namespace option for build in Forthon.
Only affected Macs. 
Fixed for Forthon 0.10.2.
If you encounter the error, update Forthon and rebuild/reinstall UEDGE.

**Comment by llnl-fesp** [comment]
The way Uedge is built using Forthon is that every package is a shared library. Forthon puts a kaboom routine in every package. It doesn't matter which kaboom is used as long as the same kaboom setup is used on the way into a routine, like exmain, as is used when an error is detected and kaboom called. The crash was occuring because the kaboom setup from the com package was used when exmain was entered but the kaboom from the bbb package was used then the error was detected and kaboom called. The new Forthon adds a loader flag, used when uedge is built, which makes the com package kaboom used all the time. Com is used because it's the first loaded when uedge is imported. The rebuild must be clean and forthon upgraded.

pip install forthon --upgrade
python setup.py clean build install
